### ISSUE TITLE
Working Example?

### ISSUE THREAD

**Issue by edcolmar** [maximepvrt/angular-google-gapi#1]
I was unable to get this working.  Is there any chance you could post a simple working example?

**Comment by maximepvrt** [comment]
This module was created to be used in MyLazyClock project (https://github.com/masterALMA2016/myLazyClock). You can watch how it works in server-gae/rest-api/src/main/webapp (api with login) and client-raspberry/core (api without login).
I will quickly create a sample example in this angular-google-gapi module.

**Comment by maximepvrt** [comment]
Hi,
Sorry about the time it took me to make an example :)
This is available here : https://github.com/maximepvrt/angular-google-gapi/tree/gh-pages (http://maximepvrt.github.io/angular-google-gapi/)
and the endpoint code is available here : https://github.com/maximepvrt/cloud-endpoints-gae

**Comment by maximepvrt** [comment]
It's a start, I will improve this example this week !
