### ISSUE TITLE
Request with parameter and body?

### ISSUE THREAD

**Issue by kusmi** [maximepvrt/angular-google-gapi#10]
I just started using your library - is it also possible to send a parameter _AND_ a request body? I use a REST update method which requires an id (parameter) and the updated JSON object is in a HTTP-PUT body.

From your examples I can only see, that you use either a parameter _OR_ a body - or do I miss something?

**Comment by maximepvrt** [comment]
It's possible to use all parameters what you want if you use a Google endpoint, it's google endpoint who link your json parameter with http parameter. This library use original js lib for Google endpoint and Google apis. If you are happy of this module please star this github project.

**Comment by kusmi** [comment]
OK - then I have to figure out how Googles endpoint APIs are doing it :-)

Thanks!

**Comment by kusmi** [comment]
If anyone is struggling with this problem as well - to add a HTTP-body to the parameters, you just have to add a "virtual" key named 'resource'. The resource parameter has to be the first argument (at least in my case) e.g.:

``` java
// Google Cloud Endpoint - Java method signature
@ApiMethod(name = "product.update", path = "products/{id}", httpMethod = HttpMethod.PUT)
public void updateProduct(@Named("id") Long id, Product product) throws NotFoundException {
…
```

``` javascript
GApi.execute('attire', 'product.update', {
            'resource': $scope.product,
            'id' : $scope.product.id
        }).then(function(resp) {
            console.log(resp);
        }, function() {
            console.log("error :(");
        });
```
