### ISSUE TITLE
Unable to pass in an authenticated user

### ISSUE THREAD

**Issue by aktary** [maximepvrt/angular-google-gapi#11]
I am authenticating my user with Passport, not your API.  How can I pass your API the oAuth data so it can make calls to Google APIs that require authentication without trying to login the user again?  I tried simply passing the user to GData.getUser() and setting GData.isLogin(true), but it doesn't work.

**Comment by maximepvrt** [comment]
You can see this issue : https://github.com/maximepvrt/angular-google-gapi/issues/9 :smile:  I don't have yet documented this method :p

**Comment by vacarsu** [comment]
If you have a fresh access token you can set the users token in the config block via: GAuth.setToken(yourToken);
This should allow you to use your passport login with the google client.  You will, however, need to get a refresh token from your passport strategy and use it to keep an up to date access token.

Edit: Also make sure you download from the develop branch, I don't think the SetToken method is on the master branch.
