### ISSUE TITLE
Error on GApi.load()

### ISSUE THREAD

**Issue by Calzzetta** [maximepvrt/angular-google-gapi#14]
Hi,

I don't know what is wrong but when I call the GApi.load(); Firefox display a error in console:

```
TypeError: b is undefined
```

Google Chrome:

```
Uncaught TypeError: Cannot read property 'replace' of undefined

trimEmptyHash @ angular.js:10611
$get @ angular.js:11421
invoke @ angular.js:4203
(anonymous function) @ angular.js:4021
getService @ angular.js:4162
invoke @ angular.js:4194
(anonymous function) @ angular.js:4021
getService @ angular.js:4162
invoke @ angular.js:4194
(anonymous function) @ angular.js:4021
getService @ angular.js:4162
invoke @ angular.js:4194
(anonymous function) @ angular.js:4025
forEach @ angular.js:323
createInjector @ angular.js:4025
doBootstrap @ angular.js:1452
bootstrap @ angular.js:1473
angularInit @ angular.js:1367
(anonymous function) @ angular.js:26304
jQuery.Callbacks.fire @ jquery.js:3099
jQuery.Callbacks.self.fireWith @ jquery.js:3211
jQuery.extend.ready @ jquery.js:3417
completed @ jquery.js:3433
```

My code is very simple:

``` javascript
var CLIENT = '.....apps.googleusercontent.com';
var BASE = 'http://localhost/_ah/api';
GApi.load('loginApi','v1',BASE);
```

I saw the error in the console but the application works. If I remove the GApi.load() call, the error disappears.

**Comment by maximepvrt** [comment]
If you remove the GApi.load(), there is no visible errors because the API calls are blocked as long as the API is not loaded. you are sure of your base ? for me it's http://localhost:8080/_ah/api

**Comment by Calzzetta** [comment]
I did a new debug on Firefox, the error was:

```
TypeError: url is undefined
```

The port is ok (I have a local server with nginx at port 80). The problem was that my project root. It was in http://localhost/elearning/_ah/api

Now I have a loop with the lazyload:
![capturar](https://cloud.githubusercontent.com/assets/6546413/7747631/c2fcde2a-ff92-11e4-8b71-ae19f33feafd.PNG)

Chrome it is starting a infinite loop, Firefox stops after some "success".

``` javascript
var CLIENT = '....apps.googleusercontent.com';
var BASE = 'http://localhost/elearning/_ah/api';

GApi.load('loginApi','v1',BASE);
GAuth.setClient(CLIENT);

GAuth.checkAuth().then(
    function () {
      console.log('success');
    },
    function() {
      console.log('error');
    }
);
```

**Comment by maximepvrt** [comment]
You watched this example ? https://github.com/maximepvrt/angular-google-gapi/tree/gh-pages
Nobody had this problem, it's strange ...

**Comment by Calzzetta** [comment]
Yes, but in the example you don't use [ocLazyLoad](https://github.com/ocombe/ocLazyLoad)
Maybe the problem is related with HTML5 url mode. If I change to another page, ocLazyLoad loads the page and the loop continue with the featured page.

In the index.html I have:

``` html
<base href="/elearning/">
```

In the router config:

``` javascript
$locationProvider.html5Mode(true);

$urlRouterProvider.otherwise( function($injector) {
  var $state = $injector.get("$state");
  $state.go("app.featured");
});
```

**Comment by maximepvrt** [comment]
I never used ocLazyLoad, sorry ...

**Comment by Calzzetta** [comment]
How could I check if the problem is related with the callback function (BASE URL)?
I don't have a route for /_ah/api and probabily is returning the default route (app.featured) that try again to load your module.

**Comment by Calzzetta** [comment]
Please mark as closed. The problem was related with gapi.

**Comment by maximepvrt** [comment]
OK :smile: you have found a solution ?
