### ISSUE TITLE
Method for retrieving access token?

### ISSUE THREAD

**Issue by vacarsu** [maximepvrt/angular-google-gapi#15]
I was wondering if there is an exposed method for retrieving an access token? Looking through the source code I couldn't find one. Here is why I need it, after the user logs in everything works until the user refreshes the page, then GApi returns unauthorized until the user logs out and logs in again.

My thought to fix this was to retrieve the access token and store it in local storage. if the user refreshes and can then set the access token using the setToken method and get everything running smoothly again.

Do you know of any other ways around this?

**Comment by maximepvrt** [comment]
I added the getToken method in develop branch :smile: 

``` javascript
GAuth.getToken().then(function(token) {
  alert('Token: ' + token);
});
```

**Comment by vacarsu** [comment]
Aweosme! Thanks!
