### ISSUE TITLE
Insecure...

### ISSUE THREAD

**Issue by lookfirst** [maximepvrt/angular-google-gapi#16]
http://maximepvrt.github.io/angular-google-gapi/#/add

Nothing prevents me from directly going to an endpoint.

You could add checks in every controller or configure ui-router to always be chained off a top level abstract route that gets executed every time, but that is ugly too.

Right now, what I'm doing is using angular-deferred-bootstrap to first load the gapi stuff, `resolve` then deals with the promises passed to the login.

I was hoping your solution might be better, but it doesn't look like it.

Thoughts on the best way to secure things? The problem is that `.run()` is not async.

**Comment by vacarsu** [comment]
In my opinion having an root view in ui router is good design. It does not have to be re-instantiated every time. just set your views on the top route and everything will inherit from it.

**Comment by dcifuen** [comment]
Maybe using the Eydis GAPI https://github.com/jonparrott/Eydis-GAPI approach, when you could defer the API loading and also know whether the API is loaded or not ($gapi.loaded, $gapi.load). 
That way, it can be easily chained if need (for example in ui-router resolves) but also can be directly accessible.

**Comment by lookfirst** [comment]
@dcifuen Thanks for the update, I'll take a look at it!

**Comment by maximepvrt** [comment]
Sorry, it's a long time since I gave news, but I modified with your tips ... look Develop branch :smile:

**Comment by lookfirst** [comment]
@maximepvrt Why do you write 'angular.module('angular-google-gapi')' all over the place? Just assign it to a variable at the top.

**Comment by maximepvrt** [comment]
@lookfirst yes it's better ... but at the end of the week, i will explode the file to one file by module and finish this new version. At the beginning, it was only a contribution that I created for a school project. I will add new features very soon
