### ISSUE TITLE
Passing object + param?

### ISSUE THREAD

**Issue by rijine** [maximepvrt/angular-google-gapi#17]

**Comment by rijine** [comment]
@maximepvrt  consider my api is like [ public Contact sample(Contact c,@Named("ids") String ids) { }]
Then how do i execute this?

**Comment by maximepvrt** [comment]
show this example : https://github.com/maximepvrt/angular-google-gapi/issues/10 :smile:

**Comment by rijine** [comment]
@maximepvrt  thanks dude...awesome..:)

**Comment by maximepvrt** [comment]
You can like this project if you love it :smile_cat:
