### ISSUE TITLE
Youtube api

### ISSUE THREAD

**Issue by besch** [maximepvrt/angular-google-gapi#18]
Hi Maxime I was wondering how to you use Youtube api with angular-google-gapi.
Is it this way?

GApi.executeAuth('youtube', 'activity', 'list').then(function(resp) {
    console.log(resp);
 });

**Comment by maximepvrt** [comment]
Show this : https://developers.google.com/apis-explorer/#p/youtube/v3/ :smile: and my example here : https://github.com/maximepvrt/angular-google-gapi/tree/gh-pages

GApi.executeAuth('youtube', 'youtube.activities.list').then(function(resp) {
console.log(resp);
});
