### ISSUE TITLE
Does not work with Admin API...

### ISSUE THREAD

**Issue by RobertAtomic** [maximepvrt/angular-google-gapi#21]
The admin API is broken into the 'directory' and 'reports' APIs.  The directory API can be loaded with GApi.load('admin', 'directory_v1'); however this library then assumes that the API calls will be prefixed with 'admin' when in fact they are prefixed with 'directory' so, a call to GApi.executeAuth('directory', 'users.list') will fail because the library has not loaded 'directory'.  A call to GApi.executeAuth('admin', 'directory.users.list') will also fail.

I can't figure out where the library maintains a list of loaded libraries, but it just silently skips a call to GApi.executeAuth('directory',... 

The library works fine for other APIs such as calendar and BigQuery, so thanks for the good work!

**Comment by maximepvrt** [comment]
Use GApi.load('admin', 'directory_v1'); with GApi.executeAuth('admin', 'directory.users.list'); https://developers.google.com/apis-explorer/#search/admin/admin/directory_v1/directory.users.list
There is no function to see apis loaded but I'll probably add it, it's a good idea. you do not think the problem is that you are not authenticated ?

**Comment by RobertAtomic** [comment]
Hi Maxime, 

Thanks for the reply.  I had already tried many variations of load and executeAuth with no success. 

Using GApi.load('admin', 'directory_v1'); with GApi.executeAuth('admin', 'directory.users.list’);

results in ‘Cannot read property ‘users’ of undefined’  

In your recommendation the library expects to find a method named admin.directory.users.list but in fact the method is directory.users.list despite the fact that it’s in the ‘admin’ api.  The admin API seems to be unique in this as it’s broken into the directory and reports APIs.  A really ugly hack to make this work is:

function runGapi(api, method, params, deferred) {

```
        var pathMethod = method.split('.');
        //ugly hack
        if(api === 'admin’){
            api = 'directory';
        }
        var api = $window.gapi.client[api];
        for(var i= 0; i < pathMethod.length; i++) {
            api = api[pathMethod[i]];
        }
        api(params).execute(function (response) {
            if (response.error) {
                deferred.reject(response);
            } else {
                deferred.resolve(response);
            }
        });
    }
```

but of course this masks the actual admin API which does have a single method and also masks the reports API so it’s obviously not a real solution to the issue.

Thanks again for the great work on this library and for looking into this issue!
Robert Jordan
Head of Systems
tel: 510 488 6641 cell: 415 233 3910 http://10.0.1.56:5000/email_signatures#
www.atomicfiction.com http://www.atomicfiction.com/

**Comment by maximepvrt** [comment]
Remplace load method in GApi with this, it's better :)

``` js
function load(api, version, url) {
            GClient.get(function (){
                $window.gapi.client.load(api, version, function() {
                    console.log(api+" "+version+" api loaded");
                    apisLoad.push(api);
                      if(api == 'admin')
                               apisLoad.push('directory')
                    executeCallbacks(api);
                }, url)
            });
        }
```

Using GApi.load('admin', 'directory_v1'); with GApi.executeAuth('directory', 'users.list’);
I think you can send a tweet to GoogleDev for they change this bug in their api :smile:

**Comment by maximepvrt** [comment]
If you like this module, you can "star" this projet
