### ISSUE TITLE
gapi.client.setApiKey is missing!

### ISSUE THREAD

**Issue by jehmehta** [maximepvrt/angular-google-gapi#27]
Hi Maximepvrt!
 Beautiful code and much easy to use for Angular Js! just one thing i guess u missed is :
gapi.client.setApiKey(APIKEY); method, please help me fix it! i really lieked your code and would want to use it but i cant since my GAE has a key protected API please append the function.
![image](https://cloud.githubusercontent.com/assets/12450045/8605294/ef87a50c-26a1-11e5-9beb-8de7260ae0d1.png)

**Comment by maximepvrt** [comment]
I have added GClient.setApiKey(apiKey) and GClient.getApiKey() methods :)
https://github.com/maximepvrt/angular-google-gapi/blob/develop/angular-google-gapi.js

**Comment by jehmehta** [comment]
Awesome, thank you so much :) will be connected to you work!
