### ISSUE TITLE
Implement a real example with setApi Key integrated

### ISSUE THREAD

**Issue by jehmehta** [maximepvrt/angular-google-gapi#29]
Can we have a real example like one of your 'gh-pages' where we see a API endpoint called and returning json object while using setApiKey(apiKey); method ?

**Comment by jehmehta** [comment]
Use my endpoints at https://iamin-events.appspot.com if you want...

**Comment by maximepvrt** [comment]
I look that tomorrow

**Comment by jehmehta** [comment]
Hi., try to use this api: in https://iamin-events.appspot.com > appUserApi > appUserApi.appUserApi.getMainListings
Using Google OAuth....

**Comment by jehmehta** [comment]
I tried implementing the Code shows a problem : 
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.3.14/$injector/modulerr?p0=angular-google-api…gleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.3.14%2Fangular.min.js%3A17%3A381)

I used the .js from Develop branch to use the setApiKey(apiKey); Method but it didnt work.

Can you try to implement your own Api and set the API_KEY ?

**Comment by maximepvrt** [comment]
I test that this monday ;)

**Comment by jehmehta** [comment]
Alright Maxime :)

**Comment by jehmehta** [comment]
Hey any progress? I can setup some backend RESTful APIs for GAE if you want...

**Comment by jehmehta** [comment]
Hey did you try?

**Comment by maximepvrt** [comment]
in develop branch, it's necessary to add ngCookies module.
