### ISSUE TITLE
Pop-up blocked by browsers

### ISSUE THREAD

**Issue by alpocr** [maximepvrt/angular-google-gapi#31]
Chrome, Firefox, Safari and Internet Explorer are blocking the sign-in pop-up. After I click to allow popups, the overflow works perfect.

I don't know if this is a bug :/

On button I have:  ng-click="login(true)".   So, "login" is a service.

``` javascript
    login: function () {
                return GAuth.login();
            },
```

I have also set "login" as a function in scope. Same problem.

Can someone help me?

**Comment by maximepvrt** [comment]
Have you looked the example ?
https://github.com/maximepvrt/angular-google-gapi/tree/gh-pages
http://maximepvrt.github.io/angular-google-gapi

**Comment by alpocr** [comment]
Yes @maximepvrt . I have implemented the following code in my controller but is still blocked my all my browsers.  

``` javascript
$scope.doLogin = function() {
            GAuth.login().then(function(){
                $state.go('home');
            });
        };
```

Any idea? What's my bad?

**Comment by maximepvrt** [comment]
and it's work in my exemple ? http://maximepvrt.github.io/angular-google-gapi in your computer ?

**Comment by bdurrer** [comment]
@maximepvrt , the example on http://maximepvrt.github.io/angular-google-gapi does have this issue too (tested today with latest FireFox).

**Comment by maximepvrt** [comment]
I do not understand :cry: if you find the problem I'm interested

**Comment by marcelomiura** [comment]
Same problem here. Any news on this?

**Comment by bdurrer** [comment]
I cross-checked the code with the google documentation and did quite some debugging. _Everything looks correct to me_. The PopBlockers of FireFox and Chrome are triggered, even when making sure that the first call is done by a user interaction with `immediate:false`. Suprisingly, IE does show the popup correctly.

I'm not sure if it has to do that angular is between the button click and the gapi, or something else entirely.

**Comment by YasharF** [comment]
The following is a javascript example (not using this module) that doesn't trigger the pop-up blocker, can it give us a clue?  http://hayageek.com/login-with-google-plus-javascript-api/

**Comment by YasharF** [comment]
Another potential clue:
From https://developers.google.com/api-client-library/javascript/features/authentication#specifying-your-client-id-and-scopes

> Note: The first call to gapi.auth.authorize can trigger popup blockers. The best way to prevent this is to set up a user-triggered action (like the Login button described here) that calls gapi.auth.authorize with immediate: false parameter.

**Comment by bdurrer** [comment]
@YasharF I checked that with the user-triggered action and the immediate parameter, it didn't work (see comment above). 

However, I did some more testing and the issue _is_ related to this module, not angular itself. Maybe it's because the call is executed with a loading-callback instead of directly in the stacktrace of the user's click action. That might lead the browser to lose the context of "user action" and its evaluated to be a "script action".

This code works as intended (It's ES6):

```
<button type="button" class="btn btn-primary btn-lg" ng-click="application.trythis()">Bypass</button>
class ApplicationController {
    trythis(){
        const myParams = {
            'clientid' : 'xxx', //You need to set client id
            'cookiepolicy' : 'single_host_origin',
            'callback' : 'loginCallback', //callback function
            /*'approvalprompt':'force',*/
            'scope' : 'https://www.googleapis.com/auth/userinfo.email'
        };
        gapi.auth.signIn(myParams);
    }
}
```

**Comment by bdurrer** [comment]
**EDIT**: Fixed my statements, 14:03.

I just tested various combinations of the two services of angular-google-gapi - and it worked!

In hindsight it's pretty obvious, I even made the correct assumption above but did not realize it's actually our user code thats breaking it! 
TL/DR: An asynchronous response is never executed in the user-action-context, so don't chain calls.

This is in the example app and **does not work**:

```
<button type="button" class="btn btn-primary btn-lg" ng-click="application.doLogin()">Login</button>
$scope.doLogin = function() {
    GAuth.checkAuth().then(
        function () {
            ifLogin();
        },
        function() {
            GAuth.login().then(function(){
                ifLogin();
            });
        }
    );
};
```

The following code works when both the GAuth.login() and GAuth.checkAuth() are executed from button events.

```
<button type="button" class="btn btn-primary btn-lg" ng-click="application.checkLogin()">Check State</button>
$scope.checkLogin = function() {
    GAuth.checkAuth();
};

<button type="button" class="btn btn-primary btn-lg" ng-click="application.doLogin()">Login</button>
$scope.doLogin = function() {
    GAuth.login().then(function(){
        ifLogin();
    });
};
```

## Conclusion

**The steps to make it works are**
- The GAuth.login() must be executed from a button event
- called it directly, not in any asynchronous callback, so do not chain GAuth.checkAuth() and GAuth.login()
- _You can call GAuth.checkAuth() whenever you want_ without breaking the code! So just call it when your application starts (e.g. in the main controller's constructor), to get the current login state and/or reconnect with a cookie. 
- it seems like you also need to call it at least once from a button click, before calling GAuth.login().

That finding is of course unsatisfactory, it might be hard to implement two buttons without it being annoying/confusing for the user.
PS: The sample @YasharF mentioned uses gapi.auth.signIn while this lib here uses gap.auth.authorize

Before my edit to this post I thought that it's only an issue with the examples and the documentation. However, I think that's not the case, but I don't have a good solution either... yet.

**Comment by bdurrer** [comment]
I can't stop digging, sorry :smile: 

The lib needs some refactoring to fix this.

The signin() currently does load() and executes the gapi code inside the promise's response. This needs to be changed, so that gapi is called directly. As a result of this, the loading of the oauth v2 api needs to be done by the user (maybe a generic init method is needed here?)

I started a pull request with a basic fix / workaround for this: GH-68. However I think it's not perfect and the implications should be considered.
