### ISSUE TITLE
offline() doesn't work

### ISSUE THREAD

**Issue by psvensson** [maximepvrt/angular-google-gapi#39]
I saw also that in the offline method, $location is used wrongly, instead of using $location.protocl, there should be $locaiton.protocol(), and the same with .host() and .port(). 

I also noticed that if you're running https, the port logic will add a (technically correct) :443 at the end of the hostname, but this will make Google OUth2 sad, since the scheme now differs from what's written (assuming you're only writing http://xxx.com)

Otherwise thanks for a small nice and comprehensible Google Authentication library for angular :)

**Comment by maximepvrt** [comment]
please explain more to https, I don't understand

**Comment by psvensson** [comment]
This was some time ago, but IIRC adding a port number to a url changes the string so that some OAuth providers thinks it's another host, for example https://foo.bar is OK but https://foo.bar:443 would be taken as something else. So I think my recommendation was to avoid adding :443 for URIs that already have https:// as protocol.

**Comment by maximepvrt** [comment]
Ok, thank you !

**Comment by rlvillacarlos** [comment]
I would like to reopen this issue but with a different problem on this line:

var origin = $location.protocol() + "//" + $location.hostname();

First and foremost this causes Error 400. 

I think it must be corrected as follows:

$location.protocol() + "://" + $location.host();

**Comment by maximepvrt** [comment]
![](https://cloud.githubusercontent.com/assets/1840026/13841804/467339f4-ec2b-11e5-9f73-ee281a1483b3.png)

**Comment by otaviosoares** [comment]
I have the same issue @rlvillacarlos 

@maximepvrt in your print you're using the native location, however the code uses the angular $location which doesn't have hostname. https://github.com/maximepvrt/angular-google-gapi/blob/master/src/factories/GAuth.factory.js#L57
