### ISSUE TITLE
Is logout working?

### ISSUE THREAD

**Issue by keiyakanno** [maximepvrt/angular-google-gapi#4]
I tried so many times to logout from Google but the function below is not working 

``` javascript
$window.gapi.auth.setToken(null);
```

Instead, I found out that I have to revoke access token according to this web page and it seems like it's working now.
https://developers.google.com/+/web/signin/disconnect

Is the function working for you?

**Comment by maximepvrt** [comment]
The GApi Framework send token value for all requests. If you change this value by null, you will not be connected. For me, it's worked, I use this for my angular-google-gapi module. But, after logout, I use a callback to redirect my user to the login page.

https://developers.google.com/api-client-library/javascript/reference/referencedocs

**Comment by joshjhargreaves** [comment]
I am also experience this issue also. If you 'logout', you are logged out until you refresh the page. This also happens in your demo.

**Comment by maximepvrt** [comment]
Use this method : 

``` javascript
app.controller('myController', ['$scope', 'GAuth', '$state',
    function myController($scope, GAuth, $state) {

    $scope.doSingup = function() {
            GAuth.logout().then(function(){
            $state.go('webapp.login');
            });
      };
    }
]);
```

**Comment by joshjhargreaves** [comment]
@maximepvrt, I don't think that's a solution to the problem. For example, if you refresh, this won't work.

 I think it's an actual 'issue' of sorts with the Google client library, presumably it's storing the OAuth token in a cookie which is loaded by the client library when it is initialised.

I have done what @keiyakanno suggested and made a call to revoke the token, but I deleting the cookie stored by the Gapi library would also work (i presume)

**Comment by maximepvrt** [comment]
GAuth.logout() disconnect your application form your google account. It doesn't disconnect your google account ! An If your application use GAuth.checkAuth(), if you reload your app, it automatically reconnects. For change this, use cookies or localstorage to save if GAuth.checkAuth() must be executed.

**Comment by roychowdhurysourav23** [comment]
I need to logout user from google account also by clicking logout button.

I used both 

1) $window.gapi.auth.setToken(null);
2) GAuth.logout().then(function(){
            $state.go('webapp.login');
            });

Both unable to logout me from my account.
Please send me any solution for the above.

**Comment by maximepvrt** [comment]
Use logout fonction ...

**Comment by roychowdhurysourav23** [comment]
Which one?

I used both but unable to logout user from his gmail account.

**Comment by maximepvrt** [comment]
You have see my example ?

**Comment by roychowdhurysourav23** [comment]
I saw the discussion on google logout and trying to use GAuth.logout() but not working.

Can you show me which example are you saying exactly

**Comment by wubbahed** [comment]
This is an issue with Google's client library.  Even they recommend calling logout directly vs. through the API - https://developers.google.com/api-client-library/javascript/help/faq#logout

**Comment by kema2014521** [comment]
could someone help me about google button Sign-in problem(I use gapi)? I use onload callback when I refresh my login page. And it's defined and all worked fine. But after login, I use stateProvider to change to another page, but the problem is when I returned to login, by using $state.go('login'). The google sign in button cannot work if I click it.

**Comment by HariVenkat1409** [comment]
*)When a person logs out redirect him to      
 window.location.href = 'https://mail.google.com/mail/u/0/?logout&hl=en';
so that none of the info is saved.
*)Page refreshes but data is secured
