### ISSUE TITLE
Does it support Services Account Authentication instead of User Oauth?

### ISSUE THREAD

**Issue by do-n-khanh** [maximepvrt/angular-google-gapi#41]
Thanks for the great code.
I dont want user to be required to login google accounts everytime. Therefore, I want to use Services Account Authentication (https://cloud.google.com/storage/docs/authentication?hl=en#service_accounts).

Could you please add support to this?
If your module has already supported this, could you please guide how to use it?

Thank you in advanced.

**Comment by maximepvrt** [comment]
I use API Client Library for JavaScript but you can add manually your google token see https://github.com/maximepvrt/angular-google-gapi/issues/9
