### ISSUE TITLE
How to include request body in executeAuth?

### ISSUE THREAD

**Issue by radiantstatic** [maximepvrt/angular-google-gapi#49]
I'm attempting to use this with the Google Calendar API, specifically the freebusy query method. https://developers.google.com/google-apps/calendar/v3/reference/freebusy

Right now I'm using:

```
GApi.executeAuth('calendar', 'freebusy.query', {'fields':'calendars'}, requestResult).then(function(resp){console.log(resp);});
```

Is there anyway to include a request body var?

Like:

```
{
 "timeMin": datetime,
"timeMax": datetime,
"timeZone": string,
"items": [
    {
     "id": string
    }
 ]
}
```

**Comment by maximepvrt** [comment]
Sorry for the long response time. I add this for the next release version.

**Comment by maximepvrt** [comment]
Test with : https://github.com/google/google-api-javascript-client/blob/master/samples/requestWithBody.html

```
GApi.executeAuth('calendar', 'freebusy.query', {
'fields':'calendars',
'resource': {
 "timeMin": datetime,
"timeMax": datetime,
"timeZone": string,
"items": [
    {
     "id": string
    }
 ]
}
}, requestResult).then(function(resp){
console.log(resp);
});
```
