### ISSUE TITLE
GApi.load is not loading

### ISSUE THREAD

**Issue by nicgirault** [maximepvrt/angular-google-gapi#52]
@maximepvrt  The request to load an api does not execute because the window.gapi.client is not fully loaded when calling window.gapi.client.load

I had to increase the timeout to 1000 to get it to work https://github.com/maximepvrt/angular-google-gapi/blob/master/angular-google-gapi.js#L44.

**Comment by nicgirault** [comment]
see https://github.com/maximepvrt/angular-google-gapi/pull/53

**Comment by maximepvrt** [comment]
see #53
