### ISSUE TITLE
Error: Load denied by X-Frame-Option

### ISSUE THREAD

**Issue by madhusudhand** [maximepvrt/angular-google-gapi#56]
Hi,

I have tried the given samples.
the run method gives me the following error.

> Load denied by X-Frame-Options: https://www.googleapis.com/admin/directory/static/proxy.html?jsh=m%3B%2F_%2Fscs%2Fapps-static%2F_%2Fjs%2Fk%3Doz.gapi.en.CseTIL-P-kk.O%2Fm%3D__features__%2Fam%3DAQ%2Frt%3Dj%2Fd%3D1%2Ft%3Dzcms%2Frs%3DAGLTcCOmH2hM0rTQueXlpsykVWGTrteBVg#parent=http%3A%2F%2Flocalhost%3A8888&rpctoken=1360801427 does not permit cross-origin framing.

I am running on localhost and i have added this origin in google api's Authorized origins.

Is there anything that i am missing?

Thanks,
Madh

**Comment by maximepvrt** [comment]
Hi,
This is not a specific bug to this library. 
Show that : http://stackoverflow.com/questions/6666423/overcoming-display-forbidden-by-x-frame-options :smile:
