### ISSUE TITLE
what is the purpose of base and how should we ask for a token as a response?

### ISSUE THREAD

**Issue by josoroma-zz** [maximepvrt/angular-google-gapi#57]
Hi!

Maybe a silly question but what is the purpose of BASE and how should we ask for a token as a response?

Thanks in advance!

**Comment by maximepvrt** [comment]
Hi,
BASE is the front door for a Google App Engine Endpoint. If you want use a Google Api, not use a BASE : see this example https://github.com/maximepvrt/angular-google-gapi#with-google-auth (calendar api).

I already use a token to authenticate users : https://github.com/maximepvrt/angular-google-gapi/blob/master/src/factories/GAuth.factory.js

**Comment by opemily** [comment]
I'm still confused by this
