### ISSUE TITLE
User gender

### ISSUE THREAD

**Issue by zivkaziv** [maximepvrt/angular-google-gapi#58]
Hi

As part of the response from Google to the API https://content.googleapis.com/oauth2/v2/userinfo we are getting the following response:
email: "zivXXXX@gmail.com"
family_name: "XXXX"
**gender: "male"**
given_name: "XXXX"
id: "XXXX22XXXXX"
link: "https://plus.google.com/XXXXXXXX"
locale: "XXX"
name: "XXXXXX"
picture: "XXXXX/-XdUIqdMkCWA/AAAAAAAAAAI/AAAAAAAAAAA/4252rscbv5M/photo.jpg"
verified_email: true

Why not to add to GData.user the gender?
Thanks
Ziv

**Comment by maximepvrt** [comment]
add this (https://www.googleapis.com/auth/userinfo.profile) in your scope 
default scope is only https://www.googleapis.com/auth/userinfo.email

**Comment by zivkaziv** [comment]
Thanks:)
Do I need additional privileges from the user for it? Or it's the same like
the default scope?

Thanks

**Comment by maximepvrt** [comment]
New scope = additional privileges :)
http://stackoverflow.com/questions/7130648/get-user-info-via-google-api

**Comment by zivkaziv** [comment]
Currently what we've done after GAuth.checkAuth() we are calling directly
to gapi.client.oauth2.userinfo.get() in order to get the gender, since it's
part of the return object from Google(we saw that this is by default the
way the project check if the user have permissions or not). Maybe you can
add to the getUser() function treatment to gender too.. This can be much
simpler:)
I hope it's clear

**Comment by maximepvrt** [comment]
No, I return the entire object in last version (v1.0.0.beta1)

**Comment by zivkaziv** [comment]
Perfect, we'll update to the latest version
