### ISSUE TITLE
GAuth.login() not passing user object in resolution

### ISSUE THREAD

**Issue by dawiong** [maximepvrt/angular-google-gapi#59]
Hi,

From the readme, it shows how to get a hold on the user object after logging in using GAuth.login(), but upon implementation on my end, it's passing undefined. I don't know if it's not intended to be passed on, but it seems it has to be passed through `login`'s deferred.resolve(). :)

Regards,
Darryl

**Comment by maximepvrt** [comment]
sorry for this bug :smile:
You can get user in GData

**Comment by dawiong** [comment]
No worries, that's what I did for the meantime.

Thanks for the fix and for creating this plugin! :smile:
