### ISSUE TITLE
npm package (version 1.0.0-beta.1) doesn't include dist dir

### ISSUE THREAD

**Issue by rwos** [maximepvrt/angular-google-gapi#62]
See title - the `package.json` has `main` set to `dist/angular-google-gapi.min.js` but there's no such file in the npm package (it _is_ in the git tag of the same name, however).

**Comment by maximepvrt** [comment]
oups :) I fix that in beta.2 :smiley:

**Comment by rwos** [comment]
:+1: thanks!

**Comment by liu-kanghui** [comment]
still no dist folder?

**Comment by maximepvrt** [comment]
No sorry
