### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by borgoya** [maximepvrt/angular-google-gapi#63]
Versions:
angularjs- 1.4.7 
angular-google-gapi- 0.1.3. 

I got this error while testing on my local server as well as on google cloud.
**Uncaught TypeError: Cannot read property 'then' of undefined**

Corresponding line no:
GApi.load('projectendpoint','v1',BASE).then( function(resp) {

Please help me to resolve this issue.

**Comment by borgoya** [comment]
The issue can be resolved by totally omitting the anonymous function. But I think it will cause problems to my app. What should I do? 

The new "**angular-google-gapi-1.0.0-beta.1**" has no such type of problem.

**Comment by maximepvrt** [comment]
yes, you must use angular-google-gapi-1.0.0-beta.1 :)
