### ISSUE TITLE
Google Identity Toolkit token - please help

### ISSUE THREAD

**Issue by LunarDevelopment** [maximepvrt/angular-google-gapi#65]
Can I change something to make this libraries auth system work with google identity toolkit, heres the token differences. 

accounts.google.com is the issuer for Google Sign-In tokens (this auth system)
identitytoolkit.google.com is the one for GitKit tokens 

Example token I want :
{"iss":"https://identitytoolkit.google.com/",
"aud":"159998488949-2ikpv6l48idu6a3bg8s35q5pvjgvd4id.apps.googleusercontent.com",
"iat":1459020243,
"exp":1460229843,
"user_id":"16340604284773755567",
"email":"test@test.com",
"provider_id":"google.com",
"verified":true,
"display_name":"Test test",
"photo_url":"https://lh4.googleusercontent.com/-B_CE0m41zOI/AAAAAAAAAAI/AAAAAAAAA5s/ifP4rpX9EgY/s96-c/photo.jpg"}

Example token this app generates :
{"iss":"accounts.google.com",
"at_hash":"VpY5OYpET78wufgz2W_z_A",
"aud":"159998488949-2ikpv6l48idu6a3bg8s35q5pvjgvd4id.apps.googleusercontent.com",
"sub":"106572272682928984834",
"email_verified":true,
"azp":"159998488949-2ikpv6l48idu6a3bg8s35q5pvjgvd4id.apps.googleusercontent.com",
"email":"test@test.com",
"iat":1459020034,
"exp":1459023634}

**Comment by maximepvrt** [comment]
I use Google API Client Library for JavaScript.
https://developers.google.com/api-client-library/javascript/features/authentication#making-the-api-request
I think is not possible, but you can set a token manually
https://eshlox.net/2015/08/18/google-cloud-endpoints-angularjs-and-json-web-tokens/
