### ISSUE TITLE
Family name & given name not coming

### ISSUE THREAD

**Issue by roychowdhurysourav23** [maximepvrt/angular-google-gapi#69]
I am using angular-google-gapi for login through gmail account.recently I am facing an issue is,when i am trying to logged in using any new made gmail account family name & given name is missing.api not returning any of name but if a tries from any of my old account all names coming perfectly.Please suggest the cause of the issue.

$window.gapi.client.oauth2.userinfo.get().execute(function(resp) {
                    if (!resp.code) {
                        $scope.guser=resp;
                        deferred.resolve();
                    } else {
                        deferred.reject();
                    }
                });

This is the code to get userinfo from google api.

**Comment by roychowdhurysourav23** [comment]
Hi Maximepvrt,
Previously this functionality was working perfectly but from past few days its causing this issue.
Issue #37 was my prev post.
Please let me know if any changes done in library file

**Comment by maximepvrt** [comment]
Don't useb `$window.gapi.client.oauth2.userinfo.get()`

I merge it soon, I think is better for you https://github.com/maximepvrt/angular-google-gapi/pull/68
