### ISSUE TITLE
GAPI only loading on cached version of site.

### ISSUE THREAD

**Issue by vacarsu** [maximepvrt/angular-google-gapi#8]
It seems like GAPI is only wanting to load on localhost and when I hit the back button on the production site. Also when the GAPI successfully loads and I'm able to click the button and login with GAuth.Login()
sending a request to Drive api results in GET https://content.googleapis.com/drive/v2/files 401 (Unauthorized). I'm assuming I need to supply a secret, but I did not see where to place this in documentation.

**Comment by maximepvrt** [comment]
Hi, to execute a request with connection required, you must use the API : GApi.executeAuth and not GApi.execute. The token is automatically given with this method and it is put in callback after the login action.

**Comment by vacarsu** [comment]
Yes, I have tried using execute and executeAuth, I think something is going wrong between Auth.login() and the callback you mentioned. I have a login form for local authorization when the user types their username and password and clicks login I verify that their login and password is correct and if so I run Auth.login() which does work, but ONLY if gapi loaded. As I said on localhost gapi loads everytime, but on production it only loads some of the time, typically when I press the back button.

**Comment by maximepvrt** [comment]
Can you send me your code ? I don't see what is the problem.

**Comment by vacarsu** [comment]
Sure I'll get a plunker up shortly.

**Comment by vacarsu** [comment]
http://plnkr.co/edit/NULBpKOJj0WYfJCA97Jj?p=preview

Here's the plunker I didn't take time to make it run, just so you can see my login controller and my drive controller along with my login form. I put the module for the login form in script.js.

**Comment by vacarsu** [comment]
As a side note when gapi does not load I find a failed request in my networks tab. 
![screen shot 2015-04-07 at 2 04 13 pm](https://cloud.githubusercontent.com/assets/11384972/7033474/1ee38ba2-dd2f-11e4-85a8-f00e2316be5c.png)

**Comment by maximepvrt** [comment]
Why have you a login and password form ? GAuth.login() open a windows for login and accept your application to discuss with your google account. Have you see my example : https://github.com/maximepvrt/angular-google-gapi/tree/gh-pages http://maximepvrt.github.io/angular-google-gapi/#/ ? I use my google endpoint, but it's the same with google apis.

**Comment by vacarsu** [comment]
The login form is for additional information, I'm storing the user info from gapi and inserting it into the user object. I do get the pop window and it works fine the problem is with gapi not loading some of the time. I've set up everything nearly identically to your example. It almost seems as if as soon as I authenticate with google, google forgets the authentication. I'm kind of at a loss as to what is going wrong.

**Comment by maximepvrt** [comment]
I found your problem ! You don't have change the scope ! use just GAuth .setScopes("https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive");
(all google drive scope are here https://developers.google.com/drive/web/scopes). Sorry, I don't have described this method.

**Comment by maximepvrt** [comment]
The setScope must be calling in this method :
app.run(['GAuth',
    function(GAuth) {
        GAuth .setScopes("https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive");
    }
]);

**Comment by vacarsu** [comment]
I added Gauth.setScopes here is how my run block looks now - 

```
  .run(['GApi', 'GAuth', function (GApi, GAuth) {
  var CLIENT = '309206812822-rn613irj145m1lm64838p6rtj5hq9pmi.apps.googleusercontent.com';

  GApi.load('drive', 'v2');
  GApi.load('calendar', 'v3');
  GAuth.setScopes("https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive");
  GAuth.setClient(CLIENT);
  }])
```

However I still get the same symptoms as before where I login, authorize with google, then get taken to the profile page, where my drive request still responds with unauthorized. I put a second login function on the parent module of my profile page and when I click that I can then see my drive files load in. How come my first GAuth.login() isn't working as expected?

**Comment by maximepvrt** [comment]
Can you update your code on plnkr or depoly in the web ?

**Comment by vacarsu** [comment]
I have it up on Heroku https://argonautimpartable.herokuapp.com/#/main Like I said gapi only loads on a cached version, so if you go to that link and click the home button in the browser, then click back and check console, You will see the GAPI's loaded.

**Comment by vacarsu** [comment]
Your suggestion of setting the scopes seems to have fixed the loading problem I was having, I also managed to fix my issues with drive, thank you for your help!
