### ISSUE TITLE
Use token acquired from Passport?

### ISSUE THREAD

**Issue by vacarsu** [maximepvrt/angular-google-gapi#9]
Is there a way to use a token acquired from Passport sending a request to an endpoint? Basically I just need the wrapper for the client and not the authorization part.

**Comment by maximepvrt** [comment]
Would you use this module to get a Google API or your API without the authorization part ? it's already possible ! If you want set manually the google token with gapi.auth.setToken (https://developers.google.com/api-client-library/javascript/reference/referencedocs#gapiauthsetToken) it's not yet possible, but I can add this feature.

**Comment by vacarsu** [comment]
Yes, that's exactly what I need. It would be awesome if you could add that feature.

**Comment by maximepvrt** [comment]
I add this feature very soon ! normally this weekend :)

**Comment by maximepvrt** [comment]
I added this feature in branch develop https://github.com/maximepvrt/angular-google-gapi/tree/develop. use GAuth.setToken(yourToken); all auth api are executed in callback after you have added a token.

**Comment by vacarsu** [comment]
Awesome, thanks alot! will try it out now.

**Comment by vacarsu** [comment]
Looks like there was a breaking change? Auth.setScopes() is now Auth.setScope().

**Comment by vacarsu** [comment]
Okay got it setup, however I am getting an error on line 232, TypeError: Cannot read property 'setToken' of undefined.

**Comment by maximepvrt** [comment]
Yes sorry, I only explained GAuth.setScope() in README, before it was an undocumented method

**Comment by maximepvrt** [comment]
I committed a fix. Sorry I didn't an example for testing, even if it's just a minor change in the code.

**Comment by vacarsu** [comment]
When trying to set the access token I get the following error: TypeError: Cannot read property 'load' of undefined.

Here is a code snippet: 
$timeout(function () {
   $http.put('/api/users/' + me._id + '/refreshtoken', me)
   .success(function (data) {
     console.log(data);
     GAuth.setToken(data.accesstoken)
     GApi.executeAuth('calendar', 'events.list').then(function(resp) {
       console.log(resp);
     }, function() {
       console.log("error :(");
     });
   });
}, 200);

**Comment by maximepvrt** [comment]
I created an example, and it seems to work. I don't have problem with "Can not read property 'load' of undefined."

**Comment by vacarsu** [comment]
I increased the timout, seems to be working. Just getting invalid credentials. So it's working! I'm in the process of getting a refresh token from passport to get a fresh access token. Thanks for your help!

**Comment by vacarsu** [comment]
I just can't seem to get passport to return a refreshToken for the life of me, not quite sure what to do at this point. :/
